### ISSUE TITLE
Duck has black background

### ISSUE THREAD

**Issue by classPythonAddike** [tamton-aquib/duck.nvim#1]
Hey, firstly, I want to say thanks for the plugin, I love watching the duck waddle around when I'm bored :smile:

Coming to my issue, the duck doesn't have a transparent background, like neovim. Instead it has a black bg around it. Do you have an idea on how to fix it?

![image](https://user-images.githubusercontent.com/72556571/143577542-2be3c9b5-6a87-4bfa-ba53-6673d75ea5e0.png)

I'm using neovim 0.5 in alacritty, running picom as my compositor

**Comment by tamton-aquib** [comment]
oops, sorry for being a lil late.

>  I love watching the duck waddle around when I'm bored.

Haha same



> Instead it has a black bg around it

Its probably the winblend property. Will check and report back

**Comment by classPythonAddike** [comment]
ok, thanks!

**Comment by tamton-aquib** [comment]
Heyyo @classPythonAddike, I've added a quick setup function for changing some values.

Heres what the default values look like:
```lua
require("duck").setup {
    character = "🦆",
    winblend = 100,   -- 0 to 100
    speed = 1,      -- optimal: 1 to 99
    width = 2
}
```

So in ur case, u could try changing `winblend`. Another way is to set highlight for the `Duck` group manually like:
```lua
vim.cmd("highlight Duck guibg=your_normal_bg")
```

Will add the docs later and lemme know if it works when u have time 😬

**Comment by classPythonAddike** [comment]
thanks a lot :grinning:

**Comment by classPythonAddike** [comment]
Just tried it out, the winblend works, tyvm!
