### ISSUE TITLE
Feature: Add kitty support

### ISSUE THREAD

**Issue by jgregoire** [tamton-aquib/duck.nvim#13]
By which I mean 🐈‍⬛ not the terminal emulator.

**Comment by tamton-aquib** [comment]
Characters are customizable.
Checkout the readme for the popular candidates:

https://github.com/tamton-aquib/duck.nvim/blob/d8a6b08af440e5a0e2b3b357e2f78bb1883272cd/README.md?plain=1#L28

**Comment by jgregoire** [comment]
Incredible work, friend!
