### ISSUE TITLE
Animals don't emit sound

### ISSUE THREAD

**Issue by Lovebird-Connoisseur** [tamton-aquib/duck.nvim#6]
Hello,

First of all, I just wanted to say that out of my 40 or so neovim plugins, this one is by far my favorite (for obvious reasons).

Now every time I open up a terminal window I have a parrot  :parrot:  to keep me company :heart:

Altough lately I noticed something that detracts from the "living with a :parrot: " experience, that being the fact that despite having neovim open the entire day, I don't get any headaches, nor do I hear ringing in my ears when I go to bed.

Sadly, the lack of :parrot:  auditory feedback tends to break the immersion for us, parrot owners.

**Comment by MordechaiHadad** [comment]
Here you go
https://www.youtube.com/watch?v=da46q0af1t8

**Comment by tamton-aquib** [comment]
> Sadly, the lack of parrot auditory feedback tends to break the immersion for us, parrot owners.

Thats sad indeed.
Maybe you could add a random range on vim.defer_fn inside a while true? 😅 

Edit:
Forgot to mention os.execute to play the sound.

**Comment by tamton-aquib** [comment]
Closing this issue for now. Feel free to reopen if theres any problem.
