### ISSUE TITLE
Feature request, BIGGER ducks

### ISSUE THREAD

**Issue by da-shalev** [tamton-aquib/duck.nvim#7]
Totally optional and for the meme.

Ascii art.... i.e. array of characters with new lines.
**Result!!!!**:
- random curse words as error messages jumping around the screen
<img width="574" alt="Screenshot 2023-06-26 at 10 29 45 PM" src="https://github.com/tamton-aquib/duck.nvim/assets/44515019/c1e667cd-c74c-467b-88cf-210556ee1dfc">

**Comment by tamton-aquib** [comment]
Heyyo @daslastic,

> Ascii art.... i.e. array of characters with new lines

Haha that would be great 🤣 !


But I'm kind of busy, this might take some time as I'm occupied with something (even though it is simple to implement)

**Comment by da-shalev** [comment]
If it takes you long enough, I'll have to go there and implement it myself! lol, no problem tho
