### ISSUE TITLE
Customize icons

### ISSUE THREAD

**Issue by peskovdev** [tamton-aquib/duck.nvim#8]
1) I happy to introduce the coolest and cutest pet: 
2) I really like an idea of making bug  in your code alive. But now it's gray. Is there any way to colorize icon?

![image](https://github.com/tamton-aquib/duck.nvim/assets/56066655/a83083b3-fb20-4fd3-b1f7-412041adf20b)

**Comment by tamton-aquib** [comment]
Heyyo @peskovdev,

> I happy to introduce the coolest and cutest pet: 

That is indeed the cutest pet. period.



I have pushed an option to specify the color:
```lua
require("duck").hatch(
	"",     -- icon
	nil,     -- speed (nil means, use default)
	"red"    -- color (can take hex values too)
)
```

Could you check if it works 😅

**Comment by peskovdev** [comment]
So fast... Impressive!

It works great! But I also found a bug: All pets will use last color, that's why I have a red penguin : )
![image](https://github.com/tamton-aquib/duck.nvim/assets/56066655/d076b8fb-b12a-4df5-a463-02a7ef1133a7)

**Comment by tamton-aquib** [comment]
@peskovdev Just pushed a small patch. Each window uses their own color now (Sorry it took time, was busy 😅 )

**Comment by peskovdev** [comment]
Now it works great (this time without any "buts")
Thank you!
